apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: mranest/rabbitmq-autocluster
        ports:
          - containerPort: 5672
            name: rabbitmq-amqp
          - containerPort: 4369
            name: rabbitmq-epmd
          - containerPort: 5671
            name: rabbitmq-amqps
          - containerPort: 15672
            name: rabbitmq-mgmt
          - containerPort: 25672
            name: rabbitmq-node
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 5
          timeoutSeconds: 1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq
        env:
        - name: HOSTNAME
          valueFrom:
           fieldRef:
            fieldPath: status.podIP
        - name: AUTOCLUSTER_LOG_LEVEL
          value: "info"
        - name: AUTOCLUSTER_CLEANUP
          value: "true"
        - name: CLEANUP_INTERVAL
          value: "60"
        - name: CLEANUP_WARN_ONLY
          value: "false"
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: erlang-cookie
        - name: RABBITMQ_DEFAULT_USER
          value: "admin"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: default-password
        - name: K8S_SERVICE_NAME
          value: "rabbitmq"
        - name: RABBITMQ_NODENAME
          value: "rabbitmq@$(HOSTNAME)"
      volumes:
        - name : rabbitmq
          emptyDir: {}
