apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
            name: redis
        command:
        - bash
        - "-c"
        - |
          MASTER_IP=$( getent hosts redis-0.redis | awk '{ print $1 }' )
          
          cp /etc/redis/templates/redis.conf /etc/redis

          if [ "$HOSTNAME" == "redis-0" ]; then
            exec /usr/local/bin/docker-entrypoint.sh redis-server /etc/redis/redis.conf
          else
            exec /usr/local/bin/docker-entrypoint.sh redis-server /etc/redis/redis.conf --slaveof $MASTER_IP 6379
          fi
        livenessProbe:
          exec:
            command: [ "redis-cli", "ping" ]
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: [ "redis-cli", "ping" ]
          initialDelaySeconds: 5
          timeoutSeconds: 1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/redis
          name: conf
        - mountPath: /etc/redis/templates
          name: config-map
          readOnly: true
      volumes:
      - name : data
        emptyDir: {}
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: redis